services:version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=${PROD_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${PROD_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${PROD_DATASOURCE_PASSWORD}
    depends_on:
      - db
    networks:
      - backspark

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${PROD_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${PROD_DATASOURCE_PASSWORD}
      - POSTGRES_DB=${PROD_DATASOURCE_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backspark

volumes:
  pgdata:

networks:
  backspark:
    driver: host