version: '3.8'
services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DEV_DATASOURCE_DB}
      - POSTGRES_USER=${DEV_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${DEV_DATASOURCE_PASSWORD}
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/backspark/data
    networks:
      - backspark

volumes:
  pgdata:

networks:
  backspark:
    driver: bridge